name: flutter_e_commerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Network
  vexana: ^2.7.0

  #Core
  kartal: ^2.3.1
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  lazy_load_scrollview: ^1.3.0

  #Navigation
  auto_route: ^3.2.4
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
